#!/usr/bin/env python3
"""parse_deliverables.py - SRC_PROC_DELIVERABLES parser (survey-level).

Emits the 9 deliverable source fields (L1F_PROC_079..087) keyed by field_name:
  - presence booleans : deliverable_{ortho,dsm,dtm,point_cloud,mesh_3d}_present
  - CRS metadata      : deliverable_{ortho,dsm,dtm,point_cloud}_crs
    (mesh carries NO CRS - OBJ/PLY/FBX have no georeferencing, presence only)

v1 reads MINIMAL data from each deliverable: file presence + CRS metadata only.
No pixel/point payload is loaded (rasters open header-only; LAS via the lazy
laspy reader) - so even the 1.16 GB ortho costs ~25 ms. Deeper raster/point-cloud
analysis is a v2 concern; v1.1 per-deliverable VIEWS re-weight the report-derived
indicators, they do not read the file payload.

Absence handling: a missing deliverable -> present=False, crs=None. Downstream
that fires DO7 PROC_DELIVERABLE_FILE_MISSING and nulls that one per-deliverable
view; processing_score itself is unaffected. Raises NO flags here (flags fire at
Stage 3b/3c).

parse(deliverables_map, project_root) -> {"fields", "parser_meta"}.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    import rasterio
except ImportError:
    rasterio = None
try:
    import laspy
except ImportError:
    laspy = None

PARSER_ID = "parse_deliverables"
PARSER_VERSION = "1.0"
SOURCE_FILE_ID = "SRC_PROC_DELIVERABLES"
STUB_MARKER = "PLACEHOLDER_STUB"

# type -> (kind, has_crs_field)
_TYPES = {
    "ortho":       ("raster", True),
    "dsm":         ("raster", True),
    "dtm":         ("raster", True),
    "point_cloud": ("lidar", True),
    "mesh_3d":     ("mesh", False),
}


def _epsg_str(crs) -> str | None:
    if crs is None:
        return None
    try:
        epsg = crs.to_epsg()
    except Exception:
        epsg = None
    if epsg:
        return f"EPSG:{epsg}"
    try:
        return crs.to_string()
    except Exception:
        return str(crs)


def _raster_crs(path: Path, notes):
    """CRS + stub flag from a GeoTIFF header (no pixels read)."""
    if rasterio is None:
        notes.append("rasterio unavailable - raster CRS not read")
        return None, None
    try:
        with rasterio.open(path) as ds:
            return _epsg_str(ds.crs), ds.tags().get("STATUS")
    except Exception as exc:
        notes.append(f"{path.name}: raster CRS read failed ({type(exc).__name__})")
        return None, None


def _lidar_crs(path: Path, notes):
    """CRS + stub flag from a LAS/LAZ header (lazy reader, no points loaded)."""
    if laspy is None:
        notes.append("laspy unavailable - point-cloud CRS not read")
        return None, None
    try:
        with laspy.open(path) as rdr:
            crs = rdr.header.parse_crs()
            sysid = (rdr.header.system_identifier or "").strip()
            return _epsg_str(crs), (STUB_MARKER if STUB_MARKER in sysid else None)
    except Exception as exc:
        notes.append(f"{path.name}: LAS CRS read failed ({type(exc).__name__})")
        return None, None


def _mesh_stub(path: Path) -> str | None:
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:512]
        return STUB_MARKER if STUB_MARKER in head else None
    except OSError:
        return None


def parse(deliverables_map: dict, project_root: Path | None = None) -> dict[str, Any]:
    root = Path(project_root) if project_root else Path(".")
    notes: list[str] = []
    fields: dict[str, Any] = {}
    per_type: dict[str, dict] = {}
    stubs: list[str] = []

    for dtype, (kind, has_crs) in _TYPES.items():
        rel = deliverables_map.get(dtype)
        path = (root / rel) if rel else None
        present = bool(path and path.is_file())
        fields[f"deliverable_{dtype}_present"] = present

        crs = None
        is_stub = None
        if present:
            if kind == "raster":
                crs, is_stub = _raster_crs(path, notes)
            elif kind == "lidar":
                crs, is_stub = _lidar_crs(path, notes)
            elif kind == "mesh":
                is_stub = _mesh_stub(path)
            if is_stub:
                stubs.append(dtype)

        if has_crs:
            fields[f"deliverable_{dtype}_crs"] = crs

        entry = {"present": present, "path": rel, "kind": kind}
        if present:
            entry["size_bytes"] = path.stat().st_size
            if is_stub:
                entry["placeholder_stub"] = True
        if has_crs:
            entry["crs"] = crs
        per_type[dtype] = entry

    present_count = sum(1 for d in _TYPES if fields[f"deliverable_{d}_present"])
    if stubs:
        notes.append(f"PLACEHOLDER stub deliverables in use: {sorted(stubs)} "
                     "(generated by make_sample_data.py; replace with real exports).")

    parser_meta = {
        "parser_id": PARSER_ID,
        "parser_version": PARSER_VERSION,
        "source_file_id": SOURCE_FILE_ID,
        "instance_found": present_count > 0,
        "read_depth": "presence + CRS metadata only (v1; no pixel/point payload loaded)",
        "crs_read_methods": {"raster": "rasterio header", "lidar": "laspy lazy header"},
        "types_present": present_count,
        "types_total": len(_TYPES),
        "placeholder_stubs": sorted(stubs),
        "per_type": per_type,
        "non_null_count": sum(1 for v in fields.values() if v is not None),
        "notes": notes,
        "flags_raised": [],
    }
    return {"fields": dict(sorted(fields.items())), "parser_meta": parser_meta}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Parse processing deliverable files (presence + CRS)")
    ap.add_argument("config", help="path to paths.json")
    args = ap.parse_args(argv)
    config_path = Path(args.config).resolve()
    with config_path.open() as fh:
        config = json.load(fh)
    out = parse(config["inputs"]["deliverables"], config_path.parent)
    print(json.dumps(out, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
